version: '3.8'
services:
  porchplus-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USERNAME=porchplus_user
      - DB_PASSWORD=porchplus_password
      - DB_DATABASE=porchplus_db
    depends_on:
      - db
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: porchplus_user
      POSTGRES_PASSWORD: porchplus_password
      POSTGRES_DB: db
    ports:
      - '5432:5432'
